quarkus.application.name=gateway
quarkus.http.port=8080
quarkus.grpc.clients.auth.host=${AUTH_HOST:localhost}
quarkus.grpc.clients.auth.port=${AUTH_GRPC_PORT:9012}
quarkus.grpc.clients.user.host=${USER_HOST:localhost}
quarkus.grpc.clients.user.port=${USER_GRPC_PORT:9011}
quarkus.grpc.clients.card.host=${CARD_HOST:localhost}
quarkus.grpc.clients.card.port=${CARD_GRPC_PORT:9004}
quarkus.grpc.clients.merchant.host=${MERCHANT_HOST:localhost}
quarkus.grpc.clients.merchant.port=${MERCHANT_GRPC_PORT:9005}
quarkus.grpc.clients.role.host=${ROLE_HOST:localhost}
quarkus.grpc.clients.role.port=${ROLE_GRPC_PORT:9006}
quarkus.grpc.clients.saldo.host=${SALDO_HOST:localhost}
quarkus.grpc.clients.saldo.port=${SALDO_GRPC_PORT:9007}
quarkus.grpc.clients.topup.host=${TOPUP_HOST:localhost}
quarkus.grpc.clients.topup.port=${TOPUP_GRPC_PORT:9008}
quarkus.grpc.clients.transaction.host=${TRANSACTION_HOST:localhost}
quarkus.grpc.clients.transaction.port=${TRANSACTION_GRPC_PORT:9009}
quarkus.grpc.clients.transfer.host=${TRANSFER_HOST:localhost}
quarkus.grpc.clients.transfer.port=${TRANSFER_GRPC_PORT:9010}
quarkus.grpc.clients.withdraw.host=${WITHDRAW_HOST:localhost}
quarkus.grpc.clients.withdraw.port=${WITHDRAW_GRPC_PORT:9013}
quarkus.grpc.clients.statsreader.host=${STATS_READER_HOST:localhost}
quarkus.grpc.clients.statsreader.port=${STATS_READER_GRPC_PORT:9015}
quarkus.smallrye-graphql.ui.enable=true
quarkus.smallrye-graphql.ui.always-include=true
quarkus.log.level=INFO
quarkus.log.category."com.sanedge".level=DEBUG
quarkus.smallrye-graphql.show-runtime-exception-message=io.grpc.StatusRuntimeException,jakarta.validation.ConstraintViolationException,com.sanedge.common.exception.ResourceNotFoundException,com.sanedge.common.exception.ResourceAlreadyExistsException,com.sanedge.common.exception.UnauthorizedException,com.sanedge.common.exception.ForbiddenException,com.sanedge.common.exception.InvalidRequestException
