-- payment_card sequences: Hibernate PanacheEntity default id generation
-- uses SEQUENCE {table}_SEQ with allocationSize = 50.
ALTER SEQUENCE IF EXISTS cards_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS cards_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS card_auth_transactions_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS card_auth_transactions_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS billing_statements_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS billing_statements_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS card_event_logs_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS card_event_logs_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS card_payments_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS card_payments_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS card_rewards_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS card_rewards_seq INCREMENT BY 50 START WITH 1;
