apiVersion: v1
kind: Service
metadata:
  name: withdraw
  namespace: payment-gateway
spec:
  selector:
    app: withdraw
  ports:
    - name: http
      port: 8093
      targetPort: 8093
    - name: grpc
      port: 9013
      targetPort: 9013
  type: ClusterIP
