-- payment_finance sequences: Hibernate PanacheEntity default id generation
-- uses SEQUENCE {table}_SEQ with allocationSize = 50.
ALTER SEQUENCE IF EXISTS saldos_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS saldos_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS saldo_mutation_operations_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS saldo_mutation_operations_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS topups_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS topups_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS transactions_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS transactions_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS transfers_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS transfers_seq INCREMENT BY 50 START WITH 1;

ALTER SEQUENCE IF EXISTS withdraws_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS withdraws_seq INCREMENT BY 50 START WITH 1;
